name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
jobs:
  linting:
    runs-on: macos-12
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Lint
      run: swiftlint
  ios_tests:
    runs-on: macos-12
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Inkable -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme Inkable -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
  catalyst_tests:
    runs-on: macos-12
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Inkable -destination "platform=macOS,variant=Mac Catalyst" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme Inkable -destination "platform=macOS,variant=Mac Catalyst" | xcpretty
